version: '3.8'

services:
  mongo:
    image: 'mongo:4.2.12'
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    command: mongod --port 27017
    networks:
      - backend

volumes:
  mongo:
    driver: local

networks:
  backend:
    name: school
